default:
    default:
        show: Content:show
        index: Content:index
        
News:
    Frontend:
        show: Content:show
        index: Content:index
    Backend:
        show: Content:show
        index: Content:index