default:
    default:
        default: Content:route
        show: Content:show
        index: Content:index
        
news:
    Frontend:
        show: Content:route
        index: Content:index
    Backend:
        show: Content:show
        index: Content:index
        
page:
    Frontend:
        show: Content:route
        index: Content:index