default:
    default:
        default: Core/Default:route
        show: Core/Default:route
        index: Core/Default:index
        
news:
    Frontend:
        index: News:index
        show: Core/Default:route
    Backend:
        show: Core/Default:show
        index: Core/Default:index
        
page:
    Frontend:
        show: Core/Default:route
        index: Core/Default:index

index:
    Frontend:
        default: Index:index
        
user:
    Frontend:
        login: User/Security:login
        profile: User/Security:profile