default:
    default:
        default: Content:route
        show: Content:route
        index: Content:index
        
news:
    Frontend:
        index: News:index
        show: Content:route
    Backend:
        show: Content:show
        index: Content:index
        
page:
    Frontend:
        show: Content:route
        index: Content:index

index:
    Frontend:
        default: Index:index