<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BrendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrendRepository extends EntityRepository
{
    /**
     * Находит категорию по id или path
     *
     * @param integer|string $slug
     * @return AppBundle\Entity\Brend
     */
    public function findBySlug($slug)
    {
        if(is_numeric($slug))
        {
            $category = $this->getEntityManager()->getRepository('AppBundle:Brend')->find($slug);
        }
        else
        {
            $category = $this->getEntityManager()->getRepository('AppBundle:Brend')->findOneBy(array('path'=>$slug));
        }
        return $category;
    }

    public function getEnabledProducts($id_brend, $limit=null, $offset=null)
    {
        $repositoryProduct = $this->getEntityManager()->getRepository('AppBundle:Product');

        return $repositoryProduct->findBy(array(
            'id_brend'=>$id_brend,
            'disabled'=>false
        ), array(), $limit, $offset);
    }
    
    /**
     * Получить производителей с активными товарами
     */
    public function getBrendsWithActiveProducts()
    {
        $em = $this->getEntityManager();
        
        $dql = "SELECT v, p
                FROM AppBundle:Brend v
                LEFT JOIN v.products p WITH p.disabled=false
                ORDER by v.title ASC";

        $q = $em->createQuery($dql);
        return $q->getResult();
    }
}
