<?php

namespace AppBundle\Repository;

/**
 * HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getEntityEntryHistory($entityCode, $entryId)
    {
        return $this->createQueryBuilder('history')
                    ->select('history')
                    ->where("history.entity=:entity and history.entryId=:entryId")
                    ->setParameter('entity', $entityCode)
                    ->setParameter('entryId', $entryId)
                    ->getQuery()
                    ->getResult();
    }
}
