<?php

namespace AppBundle\Repository;

/**
 * ContentPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModulePageRepository extends \Doctrine\ORM\EntityRepository
{
}
