<?php

namespace AppBundle\Repository;

/**
 * ContentPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModulePageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getModulePage($entityCode, $action)
    {
        $repositoryProduct = $this->getEntityManager()->getRepository('AppBundle:Core\\ModulePage');

        return $repositoryProduct->findOneBy(array(
            'entityCode'=>$entityCode,
            'action'=>$action
        ), array());
    }
}
