<?php

namespace AppBundle\Repository;

/**
 * ModulePagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModulePagesRepository extends \Doctrine\ORM\EntityRepository
{
}
