<?php

namespace AppBundle\Repository;

/**
 * NavigationItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavigationItemRepository extends \Doctrine\ORM\EntityRepository
{
}
