<?php

namespace AppBundle\Repository;

/**
 * ScrollItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScrollItemRepository extends \Doctrine\ORM\EntityRepository
{
}
