<?php

namespace AppBundle\Repository;

/**
 * ScrollRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScrollRepository extends \Doctrine\ORM\EntityRepository
{
}
