app_extra:
    resource: .
    type: extra
    
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
# Backend
app_backend:
    resource: "@AppBundle/Controller/Backend"
    type:     annotation


# js routing
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# liip
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    
logout:
    path: /logout

# hwi
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

# hwi providers
mailru_login:
    path: /login_mailru