app_extra:
    resource: .
    type: extra
    
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
# Backend
app_backend:
    resource: "@AppBundle/Controller/Backend"
    type:     annotation


# js routing
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

mail_ru:
    path: /login/check-mail-ru