security:
    
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username
        in_memory:
            memory:
                users:
                    admin:
                        password: $2a$04$sf6.LvucNkymiUSIZfA3yu5YJPa7OTcg0HxmQ87cIWqG1nU07z/6C
                        roles: 'ROLE_ADMIN'

        chain_provider:
            chain:
                providers: [ in_memory, db_provider ]

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern:   ^/
            provider: chain_provider
            
            form_login:
                login_path: /user/login
                check_path: /user/login_check
            logout:
                path:   /logout
                target: /

        admin:

            pattern:   ^/admin

            logout:
                path:   /admin/logout
                target: /admin
                
            guard:
                authenticators:
                #    - token_authenticator
                    - form_authenticator
                #entry_point: form_authenticator
                
    access_control:
        - { path: ^/admin/login,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,                  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin,             roles: ROLE_MANAGER }

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:       ROLE_MANAGER
        ROLE_MANAGER:     [ROLE_MODERATOR, ROLE_CLIENT, ROLE_USER]
        ROLE_MODERATOR:   ROLE_USER
        ROLE_CLIENT   :   ROLE_USER
