security:
    
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:

        chain_provider:
            chain:
                providers: [ in_memory, user_db ]
                        
        user_db:
            entity:
                class: AppBundle:User
                property: username

        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            
            pattern:   ^/backend
            
            anonymous: ~
            
            form_login:
                login_path: /backend/security/login
                check_path: /backend/security/login_check

            logout:
                path:   /backend/security/logout
                target: /backend
            
            provider: user_db
            
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     ^/backend
            
        main:
            
            pattern:   ^/
            
            anonymous: ~
            
            form_login:
                login_path: /security/login
                check_path: /security/login_check
            
            logout:
                path: /security/logout
                target: /
                
            provider: user_db
            
        oauth_seczone:
            anonymous: ~
            oauth:
                resource_owners:
                    mail_ru:       "/login/check-mail-ru"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: hwi_oauth.user.provider

    access_control:
            - { path: ^/security/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/backend/security/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/backend/security/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/backend/security/logout, roles: ROLE_MANAGER }
            - { path: ^/backend, roles: ROLE_MANAGER }


    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:       ROLE_MANAGER
        ROLE_MANAGER:     [ROLE_MODERATOR, ROLE_CLIENT, ROLE_USER]
        ROLE_MODERATOR:   ROLE_USER
        ROLE_CLIENT   :   ROLE_USER
