security:
    
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:

        chain_provider:
            chain:
                providers: [ in_memory, user_db ]
                        
        user_db:
            entity:
                class: AppBundle:User
                property: username

        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
        
        # без этого HWIOAuthBundle не работает... не понятно как это используется
        hwi:
            id: hwi_oauth.user.provider.entity

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            
            pattern:   ^/
            
            anonymous: ~

            form_login:
                login_path: /user/login
                check_path: /user/login_check

            logout:
                path: /user/logout
                target: /
            
            provider: user_db
            
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     ^/

            oauth:
                  resource_owners:
                      mailru:        /login_mailru
                  login_path:        /
                  use_forward:       false
                  failure_path:      /user/login

                  oauth_user_provider:
                      service: hwi_oauth.user.provider.entity
                
    access_control:
            - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/user/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/user/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/user, roles: ROLE_USER }
            - { path: ^/backend, roles: ROLE_MANAGER }


    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:       ROLE_MANAGER
        ROLE_MANAGER:     [ROLE_MODERATOR, ROLE_CLIENT, ROLE_USER]
        ROLE_MODERATOR:   ROLE_USER
        ROLE_CLIENT:      ROLE_USER
